language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

env:
  global:
    - CXX=g++-4.8
    - RUN_INTEGRATION_TESTS=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - lsof
