language: node_js

matrix:
  include:
  - node_js: "8"
    dist: trusty
  - node_js: "9"
    dist: trusty
  - node_js: "10"
    dist: bionic
  - node_js: "11"
    dist: bionic
  - node_js: "12"
    dist: bionic

env:
  global:
    - CXX=g++-4.8
    - RUN_INTEGRATION_TESTS=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - lsof

services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql --version
addons:
  postgresql: "11.2"
